### ISSUE TITLE
Screenconnect inf file points to wrong tar.bz

### ISSUE THREAD

**Issue by falkheiland** [IGEL-Community/IGEL-Custom-Partitions#1]
https://github.com/IGEL-Community/IGEL-Custom-Partitions/blob/master/CP_Source/Apps/ConnectWise_Control_ScreenConnect/screenconnect_20.1.29489.7513.inf

`file="screenconnect_20.1.29489.7513.tar.bz2"`

https://github.com/IGEL-Community/IGEL-Custom-Partitions/blob/master/CP_Source/Apps/ConnectWise_Control_ScreenConnect/screenconnect_20.1.29489.7513_etc_igel1.tar.bz2

`screenconnect_20.1.29489.7513_etc_igel1.tar.bz2`

**Comment by rneher-igel** [comment]
Well, the etc tar just has the following in it. I did not want to call it the final tar.bz2 name.  Customization: Replaced /etc/init.d with systemd / systemctl for starting and stopping ScreenConnect service (/etc/systemd/system/screenconnect.service).
