### ISSUE TITLE
Missing tar.bz2 files

### ISSUE THREAD

**Issue by gossman** [IGEL-Community/IGEL-Custom-Partitions#12]
Hi Ron, 
Just having a little play about with some of the CPs you have here but i cant seem to find the .tar.bz2 files in the actual zip files as per the layout description. 
Not sure if they have been lost somewhere but thought i would highlight it to you. Any ideas where the files are now?
Thanks

**Comment by rneher-igel** [comment]
IGEL Community does not have the rights to redistribute 3rd party software.  What we provide here is everything but the 3rd party software. Most of the items here have a build script that can be run to automate the building of the tar.bz2 file.

For example, Microsoft Teams, https://github.com/IGEL-Community/IGEL-Custom-Partitions/tree/master/CP_Source/Unified_Communications/Microsoft_Teams can be built in less than a minute following this build script on Ubuntu 18.04 system https://raw.githubusercontent.com/IGEL-Community/IGEL-Custom-Partitions/master/CP_Source/Unified_Communications/Microsoft_Teams/build-teams-cp.sh

See the video here:  https://www.linkedin.com/posts/jedayres_igelos-somethingcool-microsoftteams-activity-6740750840077926400-YjSK/

**Comment by gossman** [comment]
Absolutely understood Ron, appreciate the quick response, i will give it a go myself using the scripts.
Thank you
