### ISSUE TITLE
OTPClient v2.4.7

### ISSUE THREAD

**Issue by falkheiland** [IGEL-Community/IGEL-Custom-Partitions#15]
build the CP from the build script

1. new Icon Name:

`/custom/otpclient/usr/share/icons/hicolor/scalable/apps/com.github.paolostivanin.OTPClient.svg`

2. client does not start

```
root@IGELOS:/custom/otpclient/usr/bin# ./otpclient-cli
./otpclient-cli: error while loading shared libraries: libcotp.so.12: cannot open shared object file: No such file or directory
```

the library is getting made, i guess:

```
- Installing: /usr/lib/x86_64-linux-gnu/libcotp.so.12
```

**Comment by rneher-igel** [comment]
Can you confirm that you built this on Ubuntu 18.04 VM.

**Comment by falkheiland** [comment]
i now changed the line:

`tar vrf tmp_otpclient.tar /usr/lib/x86_64-linux-gnu/libbaseencode.so.1.0.12`

to

`tar vrf tmp_otpclient.tar /usr/lib/x86_64-linux-gnu/libcotp.so.1.2.4 /usr/lib/x86_64-linux-gnu/libbaseencode.so.1.0.12`

and redeployed the cp. that fixed the issue.

**Comment by rneher-igel** [comment]
Fixed with this update:

https://github.com/IGEL-Community/IGEL-Custom-Partitions/commit/d5855969d801c0463f9632334115a89406291d6e#diff-3072026e958a356ff4c44981cf49c72987a880c953d311b58765d8cbc1e9e507

**Comment by rneher-igel** [comment]
Updated build script to replace tar loop:

https://github.com/IGEL-Community/IGEL-Custom-Partitions/commit/f58eaeb1a9e19615aafdac2e6216bf1b2c19a6bf#diff-3072026e958a356ff4c44981cf49c72987a880c953d311b58765d8cbc1e9e507

**Comment by rneher-igel** [comment]
Closing out.
