### ISSUE TITLE
Linphone - libmediastreamer.so.11 missing

### ISSUE THREAD

**Issue by claudiobrt** [IGEL-Community/IGEL-Custom-Partitions#21]
Getting following error while running AppRun from terminal:

**error while loading shared libraries: libmediastreamer.so.11: cannot open shared object file: No such file or directory** 

Built on Ubuntu 22.04 . **libmediastreamer-base3** not supported any longer

**Comment by rneher-igel** [comment]
Please try rebuilding under 18.04.

Please confirm you are using this version

https://github.com/IGEL-Community/IGEL-Custom-Partitions/tree/master/CP_Source/Unified_Communications/Linphone_VOIP

**Comment by claudiobrt** [comment]
tried with both Linphone_VOIP and Linphone. Just downloading 16.04 and will try. Does it have to be 18.04?

Thanks for the quick response btw. [applause]

**Comment by rneher-igel** [comment]
The builder will create the file -- Linphone_VOIP-4.4.10_igel01.zip

You will need to import the profile (.xml) into UMS and the two files (.inf and .tar.bz2) to the UMS or file server.

When this CP is deployed it will call the init script with init and it will take care of linking the CP into IGEL OS file system.

So /custom/linphone/usr/lib/libmediastreamer.so.11 will be linked into /usr/lib/libmediastreamer.so.11

**Comment by rneher-igel** [comment]
Please PM me on IGEL Community on slack and we can complete debug.

**Comment by rneher-igel** [comment]
This was resolved back on 21 October. Closing this item out.

https://github.com/IGEL-Community/IGEL-Custom-Partitions/tree/master/CP_Source/Unified_Communications/Linphone_VOIP

**Comment by rneher-igel** [comment]
Closed.
