### ISSUE TITLE
Tailscale_VPN CP: tailscaled.state file not persistent

### ISSUE THREAD

**Issue by Schwanzskala** [IGEL-Community/IGEL-Custom-Partitions#25]
Tailscale saves the machinekey in the file **/var/lib/tailscale/tailscaled.state**, but in the current Tailscale Custom Partition, this file is not persistent.

If I reboot the computer, a new machinekey is generated.

When "Device Authorization" is enabled on the tailnet, the device needs to be approved each time after it is restarted, which is very cumbersome.

I was able to fix this by changing the Systemd unit file **/custom/tailscale/lib/systemd/system/tailscaled.service**:

original line:
```
ExecStart=/usr/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port=${PORT} $FLAGS
```
modified line:
```
ExecStart=/usr/sbin/tailscaled --state=/custom/tailscale/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port=${PORT} $FLAGS
```

But I'm not sure if this is the right way to do it.

**Comment by rneher-igel** [comment]
Reviewing your comments.

**Comment by Schwanzskala** [comment]
Thank you in advance. I forgot to mention that I made some more modifications in the systemd unit file, I've also commented out the following two lines:
```
#StateDirectory=tailscale
#StateDirectoryMode=0700
```
Not sure if this is really needed, if you want I can test this again, without these two lines commented out. But, as mentioned before, I'm not sure if this is the best approach at all, so testing this might not be that useful.

- More info about Tailscale "Machine certificates": https://tailscale.com/kb/1010/machine-certs/
- More info about Tailscale "Device authorization": https://tailscale.com/kb/1099/device-authorization/

**Comment by rneher-igel** [comment]
Items should be addressed now. Please rebuild.

https://github.com/IGEL-Community/IGEL-Custom-Partitions/tree/master/CP_Source/Network/Tailscale_VPN

Change history is here:

https://github.com/IGEL-Community/IGEL-Custom-Partitions/commits/master/CP_Source/Network/Tailscale_VPN
