### ISSUE TITLE
Tailscale_VPN CP: user does not have permissions to operate Tailscale

### ISSUE THREAD

**Issue by Schwanzskala** [IGEL-Community/IGEL-Custom-Partitions#26]
The desktop icon **Activate Tailscale** doesn't seem to work, at least with Tailscale 1.36.0. A terminal is started but exits immediately.

Running 'tailscale up' manually in a terminal, as user, gives an error:

**Access denied: denied
Use 'sudo tailscale up' or 'tailscale up --operator=$USER' to not require root.**

I experimented by first running 'tailscale up --operator=user' and/or 'tailscale set --operator=user' as root, and than run 'tailscale up' as user. This seems to work, however only once. After user runs 'tailscale down', user cannot run 'tailscale up' anymore until root again sets the operator to user.

Tailscale also provides 'tailscale web' which starts a local web server on port 8088 for controlling Tailscale. If I run 'tailscale web' as root, I can connect to Tailscale, as user, through this web server/web interface. This seems a nicer solution than through the terminal.

Perhaps we should consider changing the Tailscale VPN CP to use 'tailscale web' instead of 'tailscale up' in a terminal?

**Comment by rneher-igel** [comment]
Reviewing your comments.

**Comment by rneher-igel** [comment]
Items should be addressed now. Please rebuild.

https://github.com/IGEL-Community/IGEL-Custom-Partitions/tree/master/CP_Source/Network/Tailscale_VPN

Change history is here:

https://github.com/IGEL-Community/IGEL-Custom-Partitions/commits/master/CP_Source/Network/Tailscale_VPN

**Comment by Schwanzskala** [comment]
Thank you!

https://github.com/IGEL-Community/IGEL-Custom-Partitions/commit/77548714541750d33e18f2432fd080f4a6a3c013 :
```
pkexec -u root env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY
```
The above causes an authentication window/popup, which askes for the root password. (If I enter the root password it works fine.)

This is how I got this working in my test lab (without the need for root password):

UMS profile:
"System" > "Firmware Customization" > "Custom Commands" > "Desktop" > "Final desktop command" :
```
nohup tailscale web >/root/tailscale-web.log 2>&1 &
```

https://github.com/IGEL-Community/IGEL-Custom-Partitions/commit/e40ab97bfbbd49d2ffe558ac3b42d6cd81250884 :
You ended up removing 'tailscale web' from the tailscale-cp-init-script.sh script, but I think it's needed to start tailscale web the first time/after installing the CP?

**Comment by rneher-igel** [comment]
Updated profile as noted in link below...

https://github.com/IGEL-Community/IGEL-Custom-Partitions/commit/eecf588ee5b6e26b166f3a094525c9035beb18bd
