### ISSUE TITLE
Tailscale_VPN CP: Tailscale subnet routers not working

### ISSUE THREAD

**Issue by Schwanzskala** [IGEL-Community/IGEL-Custom-Partitions#27]
On the current Tailscale VPN CP, Tailscale subnet routers are not working.

To use Tailscale subnet routers on Linux, you need to add the flag '--accept-routes', for example: 'tailscale up --accept-routes'

See also: https://tailscale.com/kb/1019/subnets/#step-5-use-your-subnet-routes-from-other-machines

As an alternative we could use 'tailscale web', which will by default accept the subnet routes (and also had other advantages, see https://github.com/IGEL-Community/IGEL-Custom-Partitions/issues/26).

**Comment by rneher-igel** [comment]
Reviewing your comments.

**Comment by rneher-igel** [comment]
Items should be addressed now. Please rebuild.

https://github.com/IGEL-Community/IGEL-Custom-Partitions/tree/master/CP_Source/Network/Tailscale_VPN

Change history is here:

https://github.com/IGEL-Community/IGEL-Custom-Partitions/commits/master/CP_Source/Network/Tailscale_VPN
