### ISSUE TITLE
Tailscale_VPN CP: tailscale web not started after deploying CP

### ISSUE THREAD

**Issue by Schwanzskala** [IGEL-Community/IGEL-Custom-Partitions#29]
After deploying the Tailscale VPN Custom Partition, 'tailscale web' is not running. A reboot of the device is needed before Tailscale can be used.

I think starting of 'tailscale web' (e.g. `nohup tailscale web >/root/tailscale-web.log 2>&1 &` ) should be added below the line `sudo systemctl start tailscaled` in the tailscale-cp-init-script.sh script to resolve this issue.

**Comment by rneher-igel** [comment]
I have a note in the readme file that a reboot is needed after CP deployed.

https://github.com/IGEL-Community/IGEL-Custom-Partitions/tree/master/CP_Source/Network/Tailscale_VPN

**Comment by rneher-igel** [comment]
I will add the line to init script as well.
