### ISSUE TITLE
Unattended Installation ISO build script no longer usable due to signed Grub components

### ISSUE THREAD

**Issue by rjohnson57-chwy** [IGEL-Community/IGEL-Custom-Partitions#64]
[build-igel-iso.sh](https://github.com/IGEL-Community/IGEL-Custom-Partitions/blob/master/CP_Source/Tools_Drivers/Make_OSC_Unattended_ISO_Boot/build-igel-iso.sh )

Modifying igel.conf and attempting to boot from the newly-generated ISO with Secure Boot enabled will fail as the igel.conf.sig signature is invalidated with the unattended mode edits. Instead, the user is dropped to a `grub >` prompt. 

Unless IGEL has an official path to support this with a means to re-sign the config after modification (or if they'd find it in their hearts to expose unattended installation officially), this useful modification is no longer functional.

**Comment by rneher-igel** [comment]
Added note to the readme to request ISO image from IGEL support if Secure Boot enabled in BIOS.
